# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        couverture:
            quality : 40
            filters:
                thumbnail:
                    size: [1920, 720]
                    mode: outbound

        large:
            quality : 40
            filters:
                thumbnail:
                    size: [800, 600]
                    mode: outbound

        medium:
            quality : 40
            filters:
                thumbnail:
                    size: [340, 244]
                    mode: outbound

        midle:
            quality : 40
            filters:
                thumbnail:
                    size: [800, 400]
                    mode: outbound

        membre:
            quality : 40
            filters:
                thumbnail:
                    size: [263, 269]
                    mode: outbound

        news:
            quality : 40
            filters:
                thumbnail:
                    size: [360, 280]
                    mode: outbound

        newslarge:
            quality : 40
            filters:
                thumbnail:
                    size: [750, 395]
                    mode: outbound

        responsable:
            quality : 40
            filters:
                thumbnail:
                    size: [850, 520]
                    mode: outbound

        equipesmall:
            quality : 40
            filters:
                thumbnail:
                    size: [300, 310]
                    mode: outbound

        galerie:
            quality : 40
            filters:
                thumbnail:
                    size: [400, 300]
                    mode: outbound

        realisation:
            quality : 40
            filters:
                thumbnail:
                    size: [550, 400]
                    mode: outbound

        identity:
            quality : 40
            filters:
                thumbnail:
                    size: [300, 400]
                    mode: outbound

        thumb:
            quality : 40
            filters:
                thumbnail:
                    size: [100, 100]
                    mode: outbound

        small:
            quality : 40
            filters:
                thumbnail:
                    size: [90, 90]
                    mode: outbound

        verysmall:
            quality : 40
            filters:
                thumbnail:
                    size: [85, 75]
                    mode: outbound

        logo:
            quality : 40
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
